# Generated by Django 6.0.7 on 2026-07-28 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('medical', 'Medical'), ('accident', 'Accident'), ('security', 'Security'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='emergencies/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_assigned', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='organizations.organization')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='emergencies.emergency')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-response_time'],
            },
        ),
        migrations.AddIndex(
            model_name='emergency',
            index=models.Index(fields=['status'], name='emergencies_status_725231_idx'),
        ),
        migrations.AddIndex(
            model_name='emergency',
            index=models.Index(fields=['priority'], name='emergencies_priorit_953d44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyresponse',
            unique_together={('emergency', 'volunteer')},
        ),
    ]
