# Generated by Django 6.0.7 on 2026-07-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_reported_by_to_reporter(apps, schema_editor):
    """Preserve the reporter relationship while replacing the old field name."""
    Emergency = apps.get_model('emergencies', 'Emergency')
    Emergency.objects.filter(
        reporter__isnull=True,
        reported_by__isnull=False,
    ).update(reporter=models.F('reported_by'))


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emergencyresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='emergencyresponse',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='emergencyresponse',
            name='volunteer',
        ),
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='emergency',
            name='emergencies_status_725231_idx',
        ),
        migrations.RemoveIndex(
            model_name='emergency',
            name='emergencies_priorit_953d44_idx',
        ),
        migrations.RenameField(
            model_name='emergency',
            old_name='reported_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='emergency',
            old_name='image',
            new_name='evidence_image',
        ),
        migrations.AddField(
            model_name='emergency',
            name='emergency_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('accident', 'Road Accident'), ('medical', 'Medical Emergency'), ('landslide', 'Landslide'), ('earthquake', 'Earthquake'), ('outbreak', 'Disease Outbreak'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='reporter',
            # The prior schema stores the reporter in ``reported_by``.  Keep this
            # field nullable while this migration transitions existing rows, then
            # make it required after the old column has been removed.
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_emergencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergency',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmergencyResponse',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='category',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='priority',
        ),
        migrations.RunPython(
            copy_reported_by_to_reporter,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='reported_by',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_emergencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='title',
        ),
    ]
