# Generated by Django 6.0.7 on 2026-07-29 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrating',
            name='user',
            field=models.OneToOneField(default=None, null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_rating', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='volunteerrating',
            unique_together={('volunteer', 'user')},
        ),
        migrations.RemoveField(
            model_name='volunteerrating',
            name='rater',
        ),
    ]
