# Generated by Django 6.0.7 on 2026-07-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_alter_emergencyresponse_unique_together_and_more'),
        ('volunteers', '0003_alter_volunteerrating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the composite constraint while both of its columns still exist.
        migrations.AlterUniqueTogether(
            name='volunteerrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteerrating',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteerrating',
            name='user',
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, help_text='e.g. first aid, swimming, driving', max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='emergencies.emergency')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='volunteers.volunteerprofile')),
            ],
            options={
                'unique_together': {('emergency', 'volunteer')},
            },
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='VolunteerRating',
        ),
    ]
