# Generated by Django 6.0.7 on 2026-07-28 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_emergencies_handled', models.IntegerField(default=0)),
                ('total_volunteers', models.IntegerField(default=0)),
                ('active_organizations', models.IntegerField(default=0)),
                ('total_resources', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('emergency_count', 'Emergency Count'), ('volunteer_count', 'Volunteer Count'), ('resource_usage', 'Resource Usage'), ('organization_count', 'Organization Count')], max_length=50)),
                ('value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.dashboard')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('dashboard', 'metric_type', 'date')},
            },
        ),
    ]
